version: "3"
services:
  notebook:
    build:
      context: ./jupyter_lab_docker
    # environment:
    #   - PYTHONPATH="/usr/src:$PYTHONPATH"
    ports:
      - "8888:8888"
    volumes:
      - ./project:/usr/src
      #- ../project:/usr/src